// Code generated by protoc-gen-go. DO NOT EDIT.
// source: other/secrets/secretsparam/secretsparam.proto

/*
Package secretsparam is a generated protocol buffer package.

It is generated from these files:
	other/secrets/secretsparam/secretsparam.proto

It has these top-level messages:
	Vault_Params
	List_Vault
*/
package secretsparam

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vault_Params struct {
	ID       string `protobuf:"bytes,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	CDR_LINK string `protobuf:"bytes,2,opt,name=CDR_LINK,json=cDRLINK" json:"CDR_LINK,omitempty"`
	TEXT     string `protobuf:"bytes,3,opt,name=TEXT,json=tEXT" json:"TEXT,omitempty"`
	// string IMAGE = 4;
	IsImage bool   `protobuf:"varint,4,opt,name=IsImage,json=isImage" json:"IsImage,omitempty"`
	SizeOf  string `protobuf:"bytes,5,opt,name=SizeOf,json=sizeOf" json:"SizeOf,omitempty"`
	Access  string `protobuf:"bytes,6,opt,name=Access,json=access" json:"Access,omitempty"`
}

func (m *Vault_Params) Reset()                    { *m = Vault_Params{} }
func (m *Vault_Params) String() string            { return proto.CompactTextString(m) }
func (*Vault_Params) ProtoMessage()               {}
func (*Vault_Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Vault_Params) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Vault_Params) GetCDR_LINK() string {
	if m != nil {
		return m.CDR_LINK
	}
	return ""
}

func (m *Vault_Params) GetTEXT() string {
	if m != nil {
		return m.TEXT
	}
	return ""
}

func (m *Vault_Params) GetIsImage() bool {
	if m != nil {
		return m.IsImage
	}
	return false
}

func (m *Vault_Params) GetSizeOf() string {
	if m != nil {
		return m.SizeOf
	}
	return ""
}

func (m *Vault_Params) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

type List_Vault struct {
	ID_   string          `protobuf:"bytes,1,opt,name=ID_,json=iD" json:"ID_,omitempty"`
	List  []*Vault_Params `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
	Count int64           `protobuf:"varint,3,opt,name=Count,json=count" json:"Count,omitempty"`
}

func (m *List_Vault) Reset()                    { *m = List_Vault{} }
func (m *List_Vault) String() string            { return proto.CompactTextString(m) }
func (*List_Vault) ProtoMessage()               {}
func (*List_Vault) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *List_Vault) GetID_() string {
	if m != nil {
		return m.ID_
	}
	return ""
}

func (m *List_Vault) GetList() []*Vault_Params {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *List_Vault) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*Vault_Params)(nil), "secretsparam.Vault_Params")
	proto.RegisterType((*List_Vault)(nil), "secretsparam.List_Vault")
}

func init() { proto.RegisterFile("other/secrets/secretsparam/secretsparam.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xc9, 0xff, 0x3a, 0x16, 0x85, 0x41, 0x64, 0xf5, 0x14, 0x7a, 0xca, 0xc5, 0x08, 0xfa,
	0x04, 0xd2, 0xed, 0x61, 0xb1, 0xa8, 0xac, 0x41, 0x7a, 0x0b, 0xeb, 0xb2, 0xea, 0x42, 0x6b, 0x4a,
	0x66, 0x7b, 0xf1, 0x45, 0x7c, 0x5d, 0xc9, 0x14, 0x21, 0x39, 0x0d, 0xbf, 0x1f, 0xdf, 0xe1, 0xfb,
	0x06, 0x6e, 0xba, 0xf0, 0xe5, 0xfa, 0x5b, 0x72, 0xb6, 0x77, 0x81, 0xfe, 0xef, 0xde, 0xf4, 0x66,
	0x37, 0x81, 0x7a, 0xdf, 0x77, 0xa1, 0xc3, 0xf9, 0xd8, 0x2d, 0x7e, 0x23, 0x98, 0xbf, 0x99, 0xc3,
	0x36, 0xb4, 0x2f, 0x03, 0x13, 0x9e, 0x41, 0xac, 0xa4, 0x88, 0xca, 0xa8, 0x3a, 0xd1, 0xb1, 0x97,
	0x78, 0x05, 0xb3, 0xa5, 0xd4, 0xed, 0x5a, 0x3d, 0x3d, 0x8a, 0x98, 0x6d, 0x61, 0xa5, 0x1e, 0x10,
	0x11, 0xd2, 0x66, 0xb5, 0x69, 0x44, 0xc2, 0x3a, 0x0d, 0xab, 0x4d, 0x83, 0x02, 0x0a, 0x45, 0x6a,
	0x67, 0x3e, 0x9d, 0x48, 0xcb, 0xa8, 0x9a, 0xe9, 0xc2, 0x1f, 0x11, 0x2f, 0x21, 0x7f, 0xf5, 0x3f,
	0xee, 0xf9, 0x43, 0x64, 0x9c, 0xcf, 0x89, 0x69, 0xf0, 0x0f, 0xd6, 0x3a, 0x22, 0x91, 0x1f, 0xbd,
	0x61, 0x5a, 0x58, 0x80, 0xb5, 0xa7, 0xd0, 0x72, 0x3b, 0x3c, 0x87, 0x44, 0xc9, 0x76, 0xd4, 0xab,
	0x86, 0x74, 0xeb, 0x29, 0x88, 0xb8, 0x4c, 0xaa, 0xd3, 0xbb, 0xeb, 0x7a, 0xb2, 0x74, 0xbc, 0x48,
	0x73, 0x0e, 0x2f, 0x20, 0x5b, 0x76, 0x87, 0xef, 0xc0, 0x6d, 0x13, 0x9d, 0xd9, 0x01, 0xde, 0x73,
	0xfe, 0xc9, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdf, 0xf5, 0xcc, 0x4e, 0x44, 0x01, 0x00,
	0x00,
}
