//
//This is a proto file .
//
//Protocol Buffer is open source and free software. Protocol Buffer serialize data structure.
//This structure used during communication over network.
//
//https://developers.google.com/protocol-buffers/docs/proto3
//
//Version = 3
//
//Licence = BSD
//
//Anybody use our source code under Mozilla license.
//
//https://github.com/ali2210/WizDwarf/blob/master/LICENSE
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: piplines/protos/invoice.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pricing_Call_Request is a simple message with one binary message field called request
type Pricing_Call_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CRequest int64 `protobuf:"varint,1,opt,name=CRequest,json=cRequest,proto3" json:"CRequest,omitempty"`
}

func (x *Pricing_Call_Request) Reset() {
	*x = Pricing_Call_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piplines_protos_invoice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pricing_Call_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pricing_Call_Request) ProtoMessage() {}

func (x *Pricing_Call_Request) ProtoReflect() protoreflect.Message {
	mi := &file_piplines_protos_invoice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pricing_Call_Request.ProtoReflect.Descriptor instead.
func (*Pricing_Call_Request) Descriptor() ([]byte, []int) {
	return file_piplines_protos_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Pricing_Call_Request) GetCRequest() int64 {
	if x != nil {
		return x.CRequest
	}
	return 0
}

type Zero struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Zero) Reset() {
	*x = Zero{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piplines_protos_invoice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zero) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zero) ProtoMessage() {}

func (x *Zero) ProtoReflect() protoreflect.Message {
	mi := &file_piplines_protos_invoice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zero.ProtoReflect.Descriptor instead.
func (*Zero) Descriptor() ([]byte, []int) {
	return file_piplines_protos_invoice_proto_rawDescGZIP(), []int{1}
}

var File_piplines_protos_invoice_proto protoreflect.FileDescriptor

var file_piplines_protos_invoice_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x69, 0x70, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x69, 0x6e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x32, 0x0a, 0x14, 0x50, 0x72, 0x69, 0x63, 0x69,
	0x6e, 0x67, 0x5f, 0x43, 0x61, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x5a,
	0x65, 0x72, 0x6f, 0x32, 0x88, 0x01, 0x0a, 0x1c, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f,
	0x43, 0x61, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x03, 0x49, 0x6e, 0x63, 0x12, 0x0c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63, 0x69, 0x6e, 0x67, 0x5f, 0x43, 0x61, 0x6c, 0x6c, 0x5f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x49, 0x6e, 0x69, 0x74, 0x69,
	0x61, 0x6c, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x69, 0x6e, 0x67, 0x5f, 0x43, 0x61, 0x6c, 0x6c, 0x5f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x5a, 0x65, 0x72, 0x6f, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69,
	0x32, 0x32, 0x31, 0x30, 0x2f, 0x77, 0x69, 0x7a, 0x64, 0x77, 0x61, 0x72, 0x66, 0x2f, 0x70, 0x69,
	0x70, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_piplines_protos_invoice_proto_rawDescOnce sync.Once
	file_piplines_protos_invoice_proto_rawDescData = file_piplines_protos_invoice_proto_rawDesc
)

func file_piplines_protos_invoice_proto_rawDescGZIP() []byte {
	file_piplines_protos_invoice_proto_rawDescOnce.Do(func() {
		file_piplines_protos_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(file_piplines_protos_invoice_proto_rawDescData)
	})
	return file_piplines_protos_invoice_proto_rawDescData
}

var file_piplines_protos_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_piplines_protos_invoice_proto_goTypes = []interface{}{
	(*Pricing_Call_Request)(nil), // 0: protos.Pricing_Call_Request
	(*Zero)(nil),                 // 1: protos.Zero
}
var file_piplines_protos_invoice_proto_depIdxs = []int32{
	1, // 0: protos.Pricing_Call_Request_Service.Inc:input_type -> protos.Zero
	0, // 1: protos.Pricing_Call_Request_Service.Initial:input_type -> protos.Pricing_Call_Request
	0, // 2: protos.Pricing_Call_Request_Service.Inc:output_type -> protos.Pricing_Call_Request
	1, // 3: protos.Pricing_Call_Request_Service.Initial:output_type -> protos.Zero
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_piplines_protos_invoice_proto_init() }
func file_piplines_protos_invoice_proto_init() {
	if File_piplines_protos_invoice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_piplines_protos_invoice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pricing_Call_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_piplines_protos_invoice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Zero); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_piplines_protos_invoice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_piplines_protos_invoice_proto_goTypes,
		DependencyIndexes: file_piplines_protos_invoice_proto_depIdxs,
		MessageInfos:      file_piplines_protos_invoice_proto_msgTypes,
	}.Build()
	File_piplines_protos_invoice_proto = out.File
	file_piplines_protos_invoice_proto_rawDesc = nil
	file_piplines_protos_invoice_proto_goTypes = nil
	file_piplines_protos_invoice_proto_depIdxs = nil
}
