# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: https://www.patreon.com/enigma01
open_collective: https://opencollective.com/enigma
ko_fi:  https://ko-fi.com/enigma0493
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: https://en.liberapay.com/ali2210/
issuehunt:  https://issuehunt.io/u/ali2210
otechie:  https://otechie.com/wisdom-010
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
