package crypto


import (
	"testing"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func CryptoProofTest(t *testing.T){
	RegisterFailHandler(Fail)
	RunSpecs(t, "Crypto Proof Test suite started")
}


var _ = Describe("Crypto Proof validation relay on various parameters", func() {
	
	//  KEY GENERATED BY Curve-22519 PROOF
	Context(" key generate with curve-22519", func() {
		It("should key valid ", func() {
			Expect(PKK25519("hello world")).ShouldNot(BeEmpty())
		})
	})

	// KEY GENERATED WITHOUT ANY MATHEMATICAL PROOF
	Context("key generate without curve-22519", func() {
		It("should key valid", func() {
			Expect(BKED25519()).ShouldNot(BeEmpty())
		})
	})

	// BOB Sign the message before forward
	Context("Non-curve-22519 message signed", func() {
		Expect(BSED25519("hello world")).ShouldNot(BeEmpty())
	})

	
})