// Code generated by protoc-gen-go. DO NOT EDIT.
// source: other/bucket/storj_bucket/bucket/bucket.proto

/*
Package bucket is a generated protocol buffer package.

It is generated from these files:
	other/bucket/storj_bucket/bucket/bucket.proto

It has these top-level messages:
	Bucket_Error
*/
package bucket

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Bucket_Error_Category int32

const (
	Bucket_Error_Category_Ok    Bucket_Error_Category = 0
	Bucket_Error_Category_Error Bucket_Error_Category = 1
)

var Bucket_Error_Category_name = map[int32]string{
	0: "Ok",
	1: "Error",
}
var Bucket_Error_Category_value = map[string]int32{
	"Ok":    0,
	"Error": 1,
}

func (x Bucket_Error_Category) String() string {
	return proto.EnumName(Bucket_Error_Category_name, int32(x))
}
func (Bucket_Error_Category) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Bucket_Error struct {
	Bucket Bucket_Error_Category `protobuf:"varint,1,opt,name=bucket,enum=bucket.Bucket_Error_Category" json:"bucket,omitempty"`
}

func (m *Bucket_Error) Reset()                    { *m = Bucket_Error{} }
func (m *Bucket_Error) String() string            { return proto.CompactTextString(m) }
func (*Bucket_Error) ProtoMessage()               {}
func (*Bucket_Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Bucket_Error) GetBucket() Bucket_Error_Category {
	if m != nil {
		return m.Bucket
	}
	return Bucket_Error_Category_Ok
}

func init() {
	proto.RegisterType((*Bucket_Error)(nil), "bucket.Bucket_Error")
	proto.RegisterEnum("bucket.Bucket_Error_Category", Bucket_Error_Category_name, Bucket_Error_Category_value)
}

func init() { proto.RegisterFile("other/bucket/storj_bucket/bucket/bucket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 128 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xcd, 0x2f, 0xc9, 0x48,
	0x2d, 0xd2, 0x4f, 0x2a, 0x4d, 0xce, 0x4e, 0x2d, 0xd1, 0x2f, 0x2e, 0xc9, 0x2f, 0xca, 0x8a, 0x87,
	0x72, 0x50, 0x28, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0x36, 0x08, 0x4f, 0xc9, 0x95, 0x8b,
	0xc7, 0x09, 0xcc, 0x8a, 0x77, 0x2d, 0x2a, 0xca, 0x2f, 0x12, 0x32, 0xe5, 0x82, 0xca, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0xf0, 0x19, 0xc9, 0xea, 0x41, 0xb5, 0x21, 0xab, 0x8a, 0x77, 0x4e, 0x2c, 0x49,
	0x4d, 0xcf, 0x2f, 0xaa, 0x0c, 0x82, 0x2a, 0xd6, 0xd2, 0xe2, 0x12, 0xc5, 0xaa, 0x40, 0x88, 0x8d,
	0x8b, 0xc9, 0x3f, 0x5b, 0x80, 0x41, 0x88, 0x93, 0x8b, 0x15, 0x2c, 0x23, 0xc0, 0x98, 0xc4, 0x06,
	0x76, 0x81, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbd, 0x23, 0xfd, 0xd6, 0xb2, 0x00, 0x00, 0x00,
}
