// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors_codes/codes.proto

/*
Package error_codes is a generated protocol buffer package.

It is generated from these files:
	errors_codes/codes.proto

It has these top-level messages:
*/
package error_codes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type File_BAD_REQUEST_CODE int32

const (
	File_BAD_REQUEST_CODE_FILE_NOT_FOUND         File_BAD_REQUEST_CODE = 0
	File_BAD_REQUEST_CODE_DIRECTORY_NOT_FOUND    File_BAD_REQUEST_CODE = 1
	File_BAD_REQUEST_CODE_SAME_FILE_NAME         File_BAD_REQUEST_CODE = 2
	File_BAD_REQUEST_CODE_FILE_PERMISSION_FAILED File_BAD_REQUEST_CODE = 3
	File_BAD_REQUEST_CODE_FILE_CLOSED            File_BAD_REQUEST_CODE = 4
	File_BAD_REQUEST_CODE_WRITE_FAILED           File_BAD_REQUEST_CODE = 5
	File_BAD_REQUEST_CODE_READ_FAILED            File_BAD_REQUEST_CODE = 6
	File_BAD_REQUEST_CODE_SYNC_FAILED            File_BAD_REQUEST_CODE = 7
	File_BAD_REQUEST_CODE_FILE_NAMING_CONVERSION File_BAD_REQUEST_CODE = 8
	File_BAD_REQUEST_CODE_FILE_PATH_ERROR        File_BAD_REQUEST_CODE = 9
)

var File_BAD_REQUEST_CODE_name = map[int32]string{
	0: "FILE_NOT_FOUND",
	1: "DIRECTORY_NOT_FOUND",
	2: "SAME_FILE_NAME",
	3: "FILE_PERMISSION_FAILED",
	4: "FILE_CLOSED",
	5: "WRITE_FAILED",
	6: "READ_FAILED",
	7: "SYNC_FAILED",
	8: "FILE_NAMING_CONVERSION",
	9: "FILE_PATH_ERROR",
}
var File_BAD_REQUEST_CODE_value = map[string]int32{
	"FILE_NOT_FOUND":         0,
	"DIRECTORY_NOT_FOUND":    1,
	"SAME_FILE_NAME":         2,
	"FILE_PERMISSION_FAILED": 3,
	"FILE_CLOSED":            4,
	"WRITE_FAILED":           5,
	"READ_FAILED":            6,
	"SYNC_FAILED":            7,
	"FILE_NAMING_CONVERSION": 8,
	"FILE_PATH_ERROR":        9,
}

func (x File_BAD_REQUEST_CODE) String() string {
	return proto.EnumName(File_BAD_REQUEST_CODE_name, int32(x))
}
func (File_BAD_REQUEST_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FileDescriptor int32

const (
	FileDescriptor_READ_ONLY  FileDescriptor = 0
	FileDescriptor_WRITE_ONLY FileDescriptor = 1
	FileDescriptor_CHDIR      FileDescriptor = 2
	FileDescriptor_CHMOD      FileDescriptor = 3
)

var FileDescriptor_name = map[int32]string{
	0: "READ_ONLY",
	1: "WRITE_ONLY",
	2: "CHDIR",
	3: "CHMOD",
}
var FileDescriptor_value = map[string]int32{
	"READ_ONLY":  0,
	"WRITE_ONLY": 1,
	"CHDIR":      2,
	"CHMOD":      3,
}

func (x FileDescriptor) String() string {
	return proto.EnumName(FileDescriptor_name, int32(x))
}
func (FileDescriptor) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Router_ERROR_CODE int32

const (
	Router_ERROR_CODE_BLANK_URL         Router_ERROR_CODE = 0
	Router_ERROR_CODE_ERR_MALICIOUS_URL Router_ERROR_CODE = 1
	Router_ERROR_CODE_EMPTY_RESPONSE    Router_ERROR_CODE = 2
	Router_ERROR_CODE_EMPTY_REQUEST     Router_ERROR_CODE = 3
	Router_ERROR_CODE_HIJACK_URL        Router_ERROR_CODE = 4
)

var Router_ERROR_CODE_name = map[int32]string{
	0: "BLANK_URL",
	1: "ERR_MALICIOUS_URL",
	2: "EMPTY_RESPONSE",
	3: "EMPTY_REQUEST",
	4: "HIJACK_URL",
}
var Router_ERROR_CODE_value = map[string]int32{
	"BLANK_URL":         0,
	"ERR_MALICIOUS_URL": 1,
	"EMPTY_RESPONSE":    2,
	"EMPTY_REQUEST":     3,
	"HIJACK_URL":        4,
}

func (x Router_ERROR_CODE) String() string {
	return proto.EnumName(Router_ERROR_CODE_name, int32(x))
}
func (Router_ERROR_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Operation_ERROR_CODE int32

const (
	Operation_ERROR_CODE_EMPTY_INPUT      Operation_ERROR_CODE = 0
	Operation_ERROR_CODE_EMPTY_OUTPUT     Operation_ERROR_CODE = 1
	Operation_ERROR_CODE_GARBAGE_VALUE    Operation_ERROR_CODE = 2
	Operation_ERROR_CODE__DUMP            Operation_ERROR_CODE = 3
	Operation_ERROR_CODE_UNEXPECTED_STATE Operation_ERROR_CODE = 4
	Operation_ERROR_CODE_OVERFLOW_STATE   Operation_ERROR_CODE = 5
	Operation_ERROR_CODE_UNDERFLOW_STATE  Operation_ERROR_CODE = 6
	Operation_ERROR_CODE_MISMATCH_STATE   Operation_ERROR_CODE = 7
)

var Operation_ERROR_CODE_name = map[int32]string{
	0: "EMPTY_INPUT",
	1: "EMPTY_OUTPUT",
	2: "GARBAGE_VALUE",
	3: "_DUMP",
	4: "UNEXPECTED_STATE",
	5: "OVERFLOW_STATE",
	6: "UNDERFLOW_STATE",
	7: "MISMATCH_STATE",
}
var Operation_ERROR_CODE_value = map[string]int32{
	"EMPTY_INPUT":      0,
	"EMPTY_OUTPUT":     1,
	"GARBAGE_VALUE":    2,
	"_DUMP":            3,
	"UNEXPECTED_STATE": 4,
	"OVERFLOW_STATE":   5,
	"UNDERFLOW_STATE":  6,
	"MISMATCH_STATE":   7,
}

func (x Operation_ERROR_CODE) String() string {
	return proto.EnumName(Operation_ERROR_CODE_name, int32(x))
}
func (Operation_ERROR_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type OPTION_CODE int32

const (
	OPTION_CODE_NONE  OPTION_CODE = 0
	OPTION_CODE_OK    OPTION_CODE = 1
	OPTION_CODE_ERROR OPTION_CODE = 2
)

var OPTION_CODE_name = map[int32]string{
	0: "NONE",
	1: "OK",
	2: "ERROR",
}
var OPTION_CODE_value = map[string]int32{
	"NONE":  0,
	"OK":    1,
	"ERROR": 2,
}

func (x OPTION_CODE) String() string {
	return proto.EnumName(OPTION_CODE_name, int32(x))
}
func (OPTION_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type JSON_CODE int32

const (
	JSON_CODE_MARSHAL_ERROR   JSON_CODE = 0
	JSON_CODE_UNMARSHAL_ERROR JSON_CODE = 1
)

var JSON_CODE_name = map[int32]string{
	0: "MARSHAL_ERROR",
	1: "UNMARSHAL_ERROR",
}
var JSON_CODE_value = map[string]int32{
	"MARSHAL_ERROR":   0,
	"UNMARSHAL_ERROR": 1,
}

func (x JSON_CODE) String() string {
	return proto.EnumName(JSON_CODE_name, int32(x))
}
func (JSON_CODE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterEnum("error_codes.File_BAD_REQUEST_CODE", File_BAD_REQUEST_CODE_name, File_BAD_REQUEST_CODE_value)
	proto.RegisterEnum("error_codes.FileDescriptor", FileDescriptor_name, FileDescriptor_value)
	proto.RegisterEnum("error_codes.Router_ERROR_CODE", Router_ERROR_CODE_name, Router_ERROR_CODE_value)
	proto.RegisterEnum("error_codes.Operation_ERROR_CODE", Operation_ERROR_CODE_name, Operation_ERROR_CODE_value)
	proto.RegisterEnum("error_codes.OPTION_CODE", OPTION_CODE_name, OPTION_CODE_value)
	proto.RegisterEnum("error_codes.JSON_CODE", JSON_CODE_name, JSON_CODE_value)
}

func init() { proto.RegisterFile("errors_codes/codes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x5f, 0x72, 0xda, 0x30,
	0x10, 0xc6, 0x6d, 0xfe, 0x25, 0x2c, 0x05, 0x84, 0x92, 0xb4, 0x9d, 0x1e, 0xc1, 0x0f, 0xed, 0x43,
	0x4e, 0x20, 0xac, 0x05, 0x94, 0xd8, 0x92, 0x2b, 0xc9, 0xa4, 0x3c, 0x69, 0xda, 0xd4, 0x0f, 0xcc,
	0x74, 0x6a, 0xc6, 0xd0, 0x4b, 0xf5, 0x68, 0x3d, 0x45, 0x47, 0x12, 0x64, 0x92, 0x17, 0x06, 0xfd,
	0xf6, 0xd3, 0x7e, 0xab, 0x6f, 0x0d, 0x1f, 0x9b, 0xae, 0x6b, 0xbb, 0xa3, 0x7b, 0x6e, 0x7f, 0x36,
	0xc7, 0x2f, 0xe1, 0xf7, 0xf3, 0xa1, 0x6b, 0x4f, 0x2d, 0x9d, 0x84, 0x4a, 0x2c, 0x64, 0xff, 0x52,
	0xb8, 0x5b, 0xed, 0x7f, 0x35, 0x6e, 0xc9, 0xb8, 0xd3, 0xf8, 0xb5, 0x46, 0x63, 0x5d, 0xae, 0x38,
	0x52, 0x0a, 0xb3, 0x95, 0x28, 0xd0, 0x49, 0x65, 0xdd, 0x4a, 0xd5, 0x92, 0x93, 0x84, 0x7e, 0x80,
	0x1b, 0x2e, 0x34, 0xe6, 0x56, 0xe9, 0xdd, 0xab, 0x42, 0xea, 0xc5, 0x86, 0x95, 0xe8, 0xe2, 0x0d,
	0x56, 0x22, 0xe9, 0xd1, 0x4f, 0xf0, 0x3e, 0x1c, 0x2b, 0xd4, 0xa5, 0x30, 0x46, 0x28, 0xe9, 0x56,
	0x4c, 0x14, 0xc8, 0x49, 0x9f, 0xce, 0x61, 0x12, 0x6a, 0x79, 0xa1, 0x0c, 0x72, 0x32, 0xa0, 0x04,
	0xde, 0x3d, 0x69, 0x61, 0xf1, 0x22, 0x19, 0x7a, 0x89, 0x46, 0xc6, 0x2f, 0x60, 0xe4, 0x81, 0xd9,
	0xc9, 0xfc, 0x02, 0xae, 0x5e, 0x0c, 0x24, 0x2b, 0x85, 0x5c, 0xbb, 0x5c, 0xc9, 0x2d, 0x6a, 0xef,
	0x43, 0xae, 0xe9, 0x0d, 0xcc, 0xa3, 0x39, 0xb3, 0x1b, 0x87, 0x5a, 0x2b, 0x4d, 0xc6, 0x19, 0xc2,
	0xcc, 0xbf, 0x95, 0x37, 0xc7, 0xe7, 0x6e, 0x7f, 0x38, 0xb5, 0x1d, 0x9d, 0xc2, 0x38, 0x98, 0x28,
	0x59, 0xec, 0x48, 0x42, 0x67, 0x00, 0x71, 0x8a, 0x70, 0x4e, 0xe9, 0x18, 0x86, 0xf9, 0x86, 0x0b,
	0x4d, 0x7a, 0xf1, 0x6f, 0xa9, 0x38, 0xe9, 0x67, 0x07, 0x58, 0xe8, 0xf6, 0xcf, 0xa9, 0xe9, 0x62,
	0xe3, 0x18, 0xd7, 0x14, 0xc6, 0xcb, 0x82, 0xc9, 0x47, 0x57, 0xeb, 0x82, 0x24, 0xf4, 0x0e, 0x16,
	0xa8, 0xb5, 0x2b, 0x59, 0x21, 0x72, 0xa1, 0x6a, 0x13, 0x70, 0xc8, 0x09, 0xcb, 0xca, 0xee, 0x9c,
	0x46, 0x53, 0x29, 0x69, 0x7c, 0x4e, 0x0b, 0x98, 0x5e, 0x58, 0x88, 0x9f, 0xf4, 0xfd, 0x1c, 0x1b,
	0xf1, 0xc0, 0xf2, 0xd8, 0x6d, 0x90, 0xfd, 0x4d, 0xe1, 0x56, 0x1d, 0x9a, 0xee, 0xfb, 0x69, 0xdf,
	0xfe, 0x7e, 0xed, 0x3a, 0x87, 0x49, 0xbc, 0x2b, 0x64, 0x55, 0x5b, 0x92, 0xf8, 0x1c, 0x23, 0x50,
	0xb5, 0xf5, 0x24, 0xf5, 0xed, 0xd7, 0x4c, 0x2f, 0xd9, 0x1a, 0xdd, 0x96, 0x15, 0x35, 0xc6, 0xb7,
	0x38, 0x5e, 0x97, 0x15, 0xe9, 0xd3, 0x5b, 0x20, 0xb5, 0xc4, 0x6f, 0x15, 0xe6, 0x16, 0xb9, 0x33,
	0x96, 0x59, 0x24, 0x03, 0x3f, 0xa6, 0xda, 0xa2, 0x5e, 0x15, 0xea, 0xe9, 0xcc, 0x86, 0x3e, 0xd1,
	0x5a, 0xf2, 0x37, 0x70, 0xe4, 0x85, 0xa5, 0x30, 0x25, 0xb3, 0xf9, 0xe6, 0xcc, 0xae, 0xb2, 0x0c,
	0x26, 0xaa, 0xb2, 0x7e, 0xdd, 0x61, 0xc4, 0x6b, 0x18, 0x48, 0x25, 0x91, 0x24, 0x74, 0x04, 0x3d,
	0xf5, 0x18, 0x53, 0x8d, 0x1b, 0xe9, 0x65, 0xf7, 0x30, 0x7e, 0x30, 0x17, 0xe5, 0x02, 0xa6, 0x25,
	0xd3, 0x66, 0xc3, 0x8a, 0xf3, 0xc6, 0x92, 0x68, 0xfa, 0x16, 0xa6, 0x3f, 0x46, 0xe1, 0x3b, 0xbe,
	0xff, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x38, 0x38, 0xda, 0x06, 0xe3, 0x02, 0x00, 0x00,
}
