// This codebase desgin according to mozilla open source license.
//Redistribution , contribution and improve codebase under license
//convensions. @contact Ali Hassan AliMatrixCode@protonmail.com

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: other/jsonpb/jsonledit/jsons.proto

package jsonledit

import (
	binary "github.com/ali2210/wizdwarf/other/proteins/binary"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FILE Descriptor store json file param
type FileDescriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names    string                  `protobuf:"bytes,1,opt,name=Names,proto3" json:"Names,omitempty"`
	Types    string                  `protobuf:"bytes,2,opt,name=Types,proto3" json:"Types,omitempty"`
	Molecule []*binary.Micromolecule `protobuf:"bytes,3,rep,name=molecule,proto3" json:"molecule,omitempty"`
}

func (x *FileDescriptor) Reset() {
	*x = FileDescriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_jsonpb_jsonledit_jsons_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDescriptor) ProtoMessage() {}

func (x *FileDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_other_jsonpb_jsonledit_jsons_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDescriptor.ProtoReflect.Descriptor instead.
func (*FileDescriptor) Descriptor() ([]byte, []int) {
	return file_other_jsonpb_jsonledit_jsons_proto_rawDescGZIP(), []int{0}
}

func (x *FileDescriptor) GetNames() string {
	if x != nil {
		return x.Names
	}
	return ""
}

func (x *FileDescriptor) GetTypes() string {
	if x != nil {
		return x.Types
	}
	return ""
}

func (x *FileDescriptor) GetMolecule() []*binary.Micromolecule {
	if x != nil {
		return x.Molecule
	}
	return nil
}

var File_other_jsonpb_jsonledit_jsons_proto protoreflect.FileDescriptor

var file_other_jsonpb_jsonledit_jsons_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x6a,
	0x73, 0x6f, 0x6e, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x6c, 0x65, 0x64, 0x69, 0x74, 0x1a,
	0x22, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x73, 0x2f,
	0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x12, 0x31, 0x0a, 0x08, 0x6d, 0x6f, 0x6c, 0x65, 0x63, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x2e, 0x4d, 0x69, 0x63,
	0x72, 0x6f, 0x6d, 0x6f, 0x6c, 0x65, 0x63, 0x75, 0x6c, 0x65, 0x52, 0x08, 0x6d, 0x6f, 0x6c, 0x65,
	0x63, 0x75, 0x6c, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32, 0x32, 0x31, 0x30, 0x2f, 0x77, 0x69, 0x7a, 0x64, 0x77,
	0x61, 0x72, 0x66, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x6c, 0x65,
	0x64, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_other_jsonpb_jsonledit_jsons_proto_rawDescOnce sync.Once
	file_other_jsonpb_jsonledit_jsons_proto_rawDescData = file_other_jsonpb_jsonledit_jsons_proto_rawDesc
)

func file_other_jsonpb_jsonledit_jsons_proto_rawDescGZIP() []byte {
	file_other_jsonpb_jsonledit_jsons_proto_rawDescOnce.Do(func() {
		file_other_jsonpb_jsonledit_jsons_proto_rawDescData = protoimpl.X.CompressGZIP(file_other_jsonpb_jsonledit_jsons_proto_rawDescData)
	})
	return file_other_jsonpb_jsonledit_jsons_proto_rawDescData
}

var file_other_jsonpb_jsonledit_jsons_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_other_jsonpb_jsonledit_jsons_proto_goTypes = []interface{}{
	(*FileDescriptor)(nil),       // 0: jsonledit.FileDescriptor
	(*binary.Micromolecule)(nil), // 1: binary.Micromolecule
}
var file_other_jsonpb_jsonledit_jsons_proto_depIdxs = []int32{
	1, // 0: jsonledit.FileDescriptor.molecule:type_name -> binary.Micromolecule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_other_jsonpb_jsonledit_jsons_proto_init() }
func file_other_jsonpb_jsonledit_jsons_proto_init() {
	if File_other_jsonpb_jsonledit_jsons_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_other_jsonpb_jsonledit_jsons_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileDescriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_other_jsonpb_jsonledit_jsons_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_other_jsonpb_jsonledit_jsons_proto_goTypes,
		DependencyIndexes: file_other_jsonpb_jsonledit_jsons_proto_depIdxs,
		MessageInfos:      file_other_jsonpb_jsonledit_jsons_proto_msgTypes,
	}.Build()
	File_other_jsonpb_jsonledit_jsons_proto = out.File
	file_other_jsonpb_jsonledit_jsons_proto_rawDesc = nil
	file_other_jsonpb_jsonledit_jsons_proto_goTypes = nil
	file_other_jsonpb_jsonledit_jsons_proto_depIdxs = nil
}
