//
//This is a proto file .
//
//Protocol Buffer is open source and free software. Protocol Buffer serialize data structure.
//This structure used during communication over network.
//
//https://developers.google.com/protocol-buffers/docs/proto3
//
//Version = 3
//
//Licence = BSD
//
//Anybody use our source code under Mozilla license.
//
//https://github.com/ali2210/WizDwarf/blob/master/LICENSE
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: other/fauna/store/store.proto

package store

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error_Err_Status int32

const (
	Error_OK    Error_Err_Status = 0
	Error_ERROR Error_Err_Status = 1
)

// Enum value maps for Error_Err_Status.
var (
	Error_Err_Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
	}
	Error_Err_Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
	}
)

func (x Error_Err_Status) Enum() *Error_Err_Status {
	p := new(Error_Err_Status)
	*p = x
	return p
}

func (x Error_Err_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Err_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_other_fauna_store_store_proto_enumTypes[0].Descriptor()
}

func (Error_Err_Status) Type() protoreflect.EnumType {
	return &file_other_fauna_store_store_proto_enumTypes[0]
}

func (x Error_Err_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Err_Status.Descriptor instead.
func (Error_Err_Status) EnumDescriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{2, 0}
}

// Digital Signature store Content Ownership
type Digital_Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Public_Address  string `protobuf:"bytes,1,opt,name=Public_Address,json=publicAddress,proto3" json:"Public_Address,omitempty"`
	Private_Address string `protobuf:"bytes,2,opt,name=Private_Address,json=privateAddress,proto3" json:"Private_Address,omitempty"`
}

func (x *Digital_Signature) Reset() {
	*x = Digital_Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_fauna_store_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Digital_Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Digital_Signature) ProtoMessage() {}

func (x *Digital_Signature) ProtoReflect() protoreflect.Message {
	mi := &file_other_fauna_store_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Digital_Signature.ProtoReflect.Descriptor instead.
func (*Digital_Signature) Descriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{0}
}

func (x *Digital_Signature) GetPublic_Address() string {
	if x != nil {
		return x.Public_Address
	}
	return ""
}

func (x *Digital_Signature) GetPrivate_Address() string {
	if x != nil {
		return x.Private_Address
	}
	return ""
}

// User will change their profile picture as many times.
type Multi_D_Signature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Digital_Signature `protobuf:"bytes,1,rep,name=List,json=list,proto3" json:"List,omitempty"`
}

func (x *Multi_D_Signature) Reset() {
	*x = Multi_D_Signature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_fauna_store_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Multi_D_Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Multi_D_Signature) ProtoMessage() {}

func (x *Multi_D_Signature) ProtoReflect() protoreflect.Message {
	mi := &file_other_fauna_store_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Multi_D_Signature.ProtoReflect.Descriptor instead.
func (*Multi_D_Signature) Descriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{1}
}

func (x *Multi_D_Signature) GetList() []*Digital_Signature {
	if x != nil {
		return x.List
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string           `protobuf:"bytes,1,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	State       Error_Err_Status `protobuf:"varint,2,opt,name=State,json=state,proto3,enum=protos.Error_Err_Status" json:"State,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_fauna_store_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_other_fauna_store_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Error) GetState() Error_Err_Status {
	if x != nil {
		return x.State
	}
	return Error_OK
}

type Ledger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_fauna_store_store_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_other_fauna_store_store_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{3}
}

func (x *Ledger) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Endpoint_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	API_Key string `protobuf:"bytes,2,opt,name=API_Key,json=aPIKey,proto3" json:"API_Key,omitempty"`
}

func (x *Endpoint_Info) Reset() {
	*x = Endpoint_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_other_fauna_store_store_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endpoint_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint_Info) ProtoMessage() {}

func (x *Endpoint_Info) ProtoReflect() protoreflect.Message {
	mi := &file_other_fauna_store_store_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint_Info.ProtoReflect.Descriptor instead.
func (*Endpoint_Info) Descriptor() ([]byte, []int) {
	return file_other_fauna_store_store_proto_rawDescGZIP(), []int{4}
}

func (x *Endpoint_Info) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Endpoint_Info) GetAPI_Key() string {
	if x != nil {
		return x.API_Key
	}
	return ""
}

var File_other_fauna_store_store_proto protoreflect.FileDescriptor

var file_other_fauna_store_store_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x75, 0x6e, 0x61, 0x2f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x63, 0x0a, 0x11, 0x44, 0x69, 0x67, 0x69, 0x74,
	0x61, 0x6c, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x11,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x44, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c,
	0x5f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x7a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x5f, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x1f, 0x0a, 0x0a, 0x45,
	0x72, 0x72, 0x5f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x22, 0x1c, 0x0a, 0x06,
	0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x42, 0x0a, 0x0d, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x41, 0x50, 0x49, 0x5f, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x50, 0x49, 0x4b, 0x65, 0x79, 0x32, 0x57,
	0x0a, 0x19, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x12, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x46, 0x61, 0x75, 0x6e, 0x61, 0x4c, 0x65, 0x64, 0x67, 0x65,
	0x72, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x5f, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x69, 0x32, 0x32, 0x31, 0x30, 0x2f, 0x77, 0x69,
	0x7a, 0x64, 0x77, 0x61, 0x72, 0x66, 0x2f, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x75,
	0x6e, 0x61, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_other_fauna_store_store_proto_rawDescOnce sync.Once
	file_other_fauna_store_store_proto_rawDescData = file_other_fauna_store_store_proto_rawDesc
)

func file_other_fauna_store_store_proto_rawDescGZIP() []byte {
	file_other_fauna_store_store_proto_rawDescOnce.Do(func() {
		file_other_fauna_store_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_other_fauna_store_store_proto_rawDescData)
	})
	return file_other_fauna_store_store_proto_rawDescData
}

var file_other_fauna_store_store_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_other_fauna_store_store_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_other_fauna_store_store_proto_goTypes = []interface{}{
	(Error_Err_Status)(0),     // 0: protos.Error.Err_Status
	(*Digital_Signature)(nil), // 1: protos.Digital_Signature
	(*Multi_D_Signature)(nil), // 2: protos.Multi_D_Signature
	(*Error)(nil),             // 3: protos.Error
	(*Ledger)(nil),            // 4: protos.Ledger
	(*Endpoint_Info)(nil),     // 5: protos.Endpoint_Info
}
var file_other_fauna_store_store_proto_depIdxs = []int32{
	1, // 0: protos.Multi_D_Signature.List:type_name -> protos.Digital_Signature
	0, // 1: protos.Error.State:type_name -> protos.Error.Err_Status
	5, // 2: protos.Digital_Signature_Service.ConnectFaunaLedger:input_type -> protos.Endpoint_Info
	3, // 3: protos.Digital_Signature_Service.ConnectFaunaLedger:output_type -> protos.Error
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_other_fauna_store_store_proto_init() }
func file_other_fauna_store_store_proto_init() {
	if File_other_fauna_store_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_other_fauna_store_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Digital_Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_fauna_store_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Multi_D_Signature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_fauna_store_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_fauna_store_store_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ledger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_other_fauna_store_store_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endpoint_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_other_fauna_store_store_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_other_fauna_store_store_proto_goTypes,
		DependencyIndexes: file_other_fauna_store_store_proto_depIdxs,
		EnumInfos:         file_other_fauna_store_store_proto_enumTypes,
		MessageInfos:      file_other_fauna_store_store_proto_msgTypes,
	}.Build()
	File_other_fauna_store_store_proto = out.File
	file_other_fauna_store_store_proto_rawDesc = nil
	file_other_fauna_store_store_proto_goTypes = nil
	file_other_fauna_store_store_proto_depIdxs = nil
}
